<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
<xacro:include filename="$(find drone_description)/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find Drone)/urdf/Drone.xacro" />


<robot
  name="Drone">
  <link
    name="base_link">
    <inertial>
      <origin
        xyz="0.0580662945969179 -0.207894379164459 0.0471735058092778"
        rpy="0 0 0" />
      <mass
        value="0.650946416276571" />
      <inertia
        ixx="0.000998380638155361"
        ixy="-6.79564763637663E-07"
        ixz="2.19156341137026E-05"
        iyy="0.000951256875688883"
        iyz="-9.17864447372248E-06"
        izz="0.00187770151323068" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/base_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/base_link.STL" />
      </geometry>
    </collision>
  </link>
  <link
    name="link_1">
    <inertial>
      <origin
        xyz="-5.4133E-05 0.022538 -0.028037"
        rpy="0 0 0" />
      <mass
        value="0.0021185" />
      <inertia
        ixx="2.5411E-06"
        ixy="-1.3381E-08"
        ixz="-3.3432E-09"
        iyy="2.5608E-06"
        iyz="-6.1336E-08"
        izz="9.8074E-08" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="prop_1"
    type="revolute">
    <origin
      xyz="-0.13942 -0.40819 0.088186"
      rpy="1.6071 0.00064276 0.73548" />
    <parent
      link="base_link" />
    <child
      link="link_1" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3.14"
      upper="3.14"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="link_2">
    <inertial>
      <origin
        xyz="-5.4134E-05 0.019895 -0.028037"
        rpy="0 0 0" />
      <mass
        value="0.0021185" />
      <inertia
        ixx="2.5411E-06"
        ixy="-1.3381E-08"
        ixz="-3.3434E-09"
        iyy="2.5608E-06"
        iyz="-6.1336E-08"
        izz="9.8073E-08" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_2.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="prop_2"
    type="revolute">
    <origin
      xyz="0.2496 -0.41775 0.0809"
      rpy="1.5773 0.035764 -0.63755" />
    <parent
      link="base_link" />
    <child
      link="link_2" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3.14"
      upper="3.14"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="link_3">
    <inertial>
      <origin
        xyz="-5.4078E-05 0.022548 -0.028037"
        rpy="0 0 0" />
      <mass
        value="0.0021186" />
      <inertia
        ixx="2.5411E-06"
        ixy="-1.3381E-08"
        ixz="-3.3442E-09"
        iyy="2.5608E-06"
        iyz="-6.1336E-08"
        izz="9.8075E-08" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_3.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_3.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="prop_3"
    type="revolute">
    <origin
      xyz="0.25622 -0.019426 0.08865"
      rpy="1.6069 0.0042025 0.63734" />
    <parent
      link="base_link" />
    <child
      link="link_3" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3.14"
      upper="3.14"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="link_4">
    <inertial>
      <origin
        xyz="-5.4132E-05 0.019781 -0.028037"
        rpy="0 0 0" />
      <mass
        value="0.0021185" />
      <inertia
        ixx="2.5411E-06"
        ixy="-1.3381E-08"
        ixz="-3.3433E-09"
        iyy="2.5608E-06"
        iyz="-6.1336E-08"
        izz="9.8073E-08" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_4.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://Drone/meshes/link_4.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="prop_4"
    type="revolute">
    <origin
      xyz="-0.13587 -0.019748 0.10116"
      rpy="1.5761 0.035965 -0.67175" />
    <parent
      link="base_link" />
    <child
      link="link_4" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3.14"
      upper="3.14"
      effort="0"
      velocity="0" />
  </joint>

<joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>